/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminSiteVisitsRouteImport } from './routes/admin.site-visits'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminSalesRouteImport } from './routes/admin.sales'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminProjectsRouteImport } from './routes/admin.projects'
import { Route as AdminPlotsRouteImport } from './routes/admin.plots'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminEnquiriesRouteImport } from './routes/admin.enquiries'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AdminBookingsRouteImport } from './routes/admin.bookings'

const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSiteVisitsRoute = AdminSiteVisitsRouteImport.update({
  id: '/admin/site-visits',
  path: '/admin/site-visits',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSalesRoute = AdminSalesRouteImport.update({
  id: '/admin/sales',
  path: '/admin/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProjectsRoute = AdminProjectsRouteImport.update({
  id: '/admin/projects',
  path: '/admin/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPlotsRoute = AdminPlotsRouteImport.update({
  id: '/admin/plots',
  path: '/admin/plots',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/admin/notifications',
  path: '/admin/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEnquiriesRoute = AdminEnquiriesRouteImport.update({
  id: '/admin/enquiries',
  path: '/admin/enquiries',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/admin/customers',
  path: '/admin/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/admin/bookings',
  path: '/admin/bookings',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/plots': typeof AdminPlotsRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/sales': typeof AdminSalesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/site-visits': typeof AdminSiteVisitsRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/plots': typeof AdminPlotsRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/sales': typeof AdminSalesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/site-visits': typeof AdminSiteVisitsRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/plots': typeof AdminPlotsRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/sales': typeof AdminSalesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/site-visits': typeof AdminSiteVisitsRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin/bookings'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/enquiries'
    | '/admin/login'
    | '/admin/notifications'
    | '/admin/plots'
    | '/admin/projects'
    | '/admin/reports'
    | '/admin/sales'
    | '/admin/settings'
    | '/admin/site-visits'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin/bookings'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/enquiries'
    | '/admin/login'
    | '/admin/notifications'
    | '/admin/plots'
    | '/admin/projects'
    | '/admin/reports'
    | '/admin/sales'
    | '/admin/settings'
    | '/admin/site-visits'
    | '/admin'
  id:
    | '__root__'
    | '/admin/bookings'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/enquiries'
    | '/admin/login'
    | '/admin/notifications'
    | '/admin/plots'
    | '/admin/projects'
    | '/admin/reports'
    | '/admin/sales'
    | '/admin/settings'
    | '/admin/site-visits'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminEnquiriesRoute: typeof AdminEnquiriesRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminPlotsRoute: typeof AdminPlotsRoute
  AdminProjectsRoute: typeof AdminProjectsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSalesRoute: typeof AdminSalesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSiteVisitsRoute: typeof AdminSiteVisitsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/site-visits': {
      id: '/admin/site-visits'
      path: '/admin/site-visits'
      fullPath: '/admin/site-visits'
      preLoaderRoute: typeof AdminSiteVisitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sales': {
      id: '/admin/sales'
      path: '/admin/sales'
      fullPath: '/admin/sales'
      preLoaderRoute: typeof AdminSalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/projects': {
      id: '/admin/projects'
      path: '/admin/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AdminProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/plots': {
      id: '/admin/plots'
      path: '/admin/plots'
      fullPath: '/admin/plots'
      preLoaderRoute: typeof AdminPlotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/admin/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/enquiries': {
      id: '/admin/enquiries'
      path: '/admin/enquiries'
      fullPath: '/admin/enquiries'
      preLoaderRoute: typeof AdminEnquiriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/admin/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/admin/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AdminBookingsRoute: AdminBookingsRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminEnquiriesRoute: AdminEnquiriesRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminPlotsRoute: AdminPlotsRoute,
  AdminProjectsRoute: AdminProjectsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSalesRoute: AdminSalesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSiteVisitsRoute: AdminSiteVisitsRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
