// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

// Returns true when the project is running without Supabase credentials.
export function isSupabaseUnconfigured(): boolean {
  const url = (typeof import.meta !== 'undefined' ? import.meta.env?.VITE_SUPABASE_URL : undefined)
    || (typeof process !== 'undefined' ? process.env?.SUPABASE_URL : undefined);
  const key = (typeof import.meta !== 'undefined' ? import.meta.env?.VITE_SUPABASE_PUBLISHABLE_KEY : undefined)
    || (typeof process !== 'undefined' ? process.env?.SUPABASE_PUBLISHABLE_KEY : undefined);
  return !url || !key;
}

// A deep no-op proxy that never throws.
// Used as a safe stand-in when Supabase credentials are absent.
function createNoOpProxy(): any {
  const handler: ProxyHandler<object> = {
    get(_, prop) {
      // auth.getSession / auth.getUser etc. return a safe shape
      if (prop === 'auth') {
        return new Proxy({}, {
          get(__, authProp) {
            if (authProp === 'getSession') return async () => {
              const mockSession = localStorage.getItem('mock_admin_session');
              return { data: { session: mockSession ? JSON.parse(mockSession) : null }, error: null };
            };
            if (authProp === 'getUser') return async () => {
              const mockSession = localStorage.getItem('mock_admin_session');
              return { data: { user: mockSession ? JSON.parse(mockSession).user : null }, error: null };
            };
            if (authProp === 'signUp' || authProp === 'signInWithPassword') return async (opts: any) => {
              const email = opts?.email || 'mock@admin.com';
              const mockSession = { user: { id: 'mock-admin-id', email }, access_token: 'mock-token' };
              localStorage.setItem('mock_admin_session', JSON.stringify(mockSession));
              return { data: { user: mockSession.user, session: mockSession }, error: null };
            };
            if (authProp === 'signOut') return async () => {
              localStorage.removeItem('mock_admin_session');
              return { error: null };
            };
            if (authProp === 'onAuthStateChange') return () => ({ data: { subscription: { unsubscribe: () => {} } } });
            return async () => ({ data: { session: null, user: null }, error: null });
          },
        });
      }
      // from(...).select / insert / update / delete → empty results
      if (prop === 'from') {
        return () => new Proxy({}, {
          get(__, method) {
            const chainable = () => new Proxy({}, {
              get(__, inner) {
                if (inner === 'then') return undefined; // not a thenable unless called
                return chainable();
              },
            });
            if (['select', 'insert', 'update', 'delete', 'upsert'].includes(String(method))) {
              return () => ({
                data: [],
                error: null,
                count: 0,
                // make it chainable
                eq: () => ({ data: null, error: null, maybeSingle: async () => ({ data: null, error: null }), single: async () => ({ data: null, error: null }) }),
                order: () => ({ data: [], error: null }),
                limit: () => ({ data: [], error: null }),
                in: () => ({ data: [], error: null }),
                neq: () => ({ data: [], error: null }),
                contains: () => ({ data: [], error: null }),
                or: () => ({ data: [], error: null }),
                maybeSingle: async () => ({ data: { role: 'admin' }, error: null }),
                single: async () => ({ data: { role: 'admin' }, error: null }),
              });
            }
            if (method === 'rpc') return async () => ({ data: false, error: null });
            return chainable();
          },
        });
      }
      if (prop === 'rpc') return async () => ({ data: false, error: null });
      return () => ({ data: null, error: null });
    },
  };
  return new Proxy({}, handler);
}

function createSupabaseClient() {
  const SUPABASE_URL =
    (typeof import.meta !== 'undefined' ? import.meta.env?.VITE_SUPABASE_URL : undefined)
    || (typeof process !== 'undefined' ? process.env?.SUPABASE_URL : undefined);
  const SUPABASE_PUBLISHABLE_KEY =
    (typeof import.meta !== 'undefined' ? import.meta.env?.VITE_SUPABASE_PUBLISHABLE_KEY : undefined)
    || (typeof process !== 'undefined' ? process.env?.SUPABASE_PUBLISHABLE_KEY : undefined);

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
    ];
    console.warn(
      `[Supabase] Running in Development Mode — missing env var(s): ${missing.join(', ')}.\n` +
      `Set VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY in your .env file to connect to Supabase.`,
    );
    // Return a no-op proxy instead of throwing — prevents global crash
    return createNoOpProxy() as ReturnType<typeof createClient<Database>>;
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase as object, prop, receiver);
  },
});
